spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoang_tour
    username: hoang_tour
    password: hoang123@
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.type.descriptor:
      sql: trace
      type: trace
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: trace

jwt:
  accessSecretKey: 1jF6cIqwJBCjgKFFCGOnTZ16xF7gN04U2lhqez9j0CMKrtIJ3JZva2cVlF1KbpryXoGl3mi96Y8+2kvveqp9lQ==
  refreshSecretKey: hX8rYzawftO1goU9uV6oYomS4XXhEDHx

image:
  basePath: /Desktop/hoang-tour/images
